### ISSUE TITLE
Selecting color changes color for all notes, not just one being created.

### ISSUE THREAD

**Issue by cjlovelace** [aditya-singh9/notem#16]
I'm noticing that color selection changes the color of all existing notes. 

For usability, I'm wondering if there are two new changes to be made:

1. Selecting a color changes the color of only newly created notes. This allows users to sort notes by color for different purposes or general organization.
2. Already posted notes have some sort of color change functionality, perhaps on the note itself.

I could see something along the lines of below. Some design changes would potentially need to consider smaller sized notes so that colored selectors don't overlap with boundaries of note border.
![notes marker](https://i.imgur.com/lO1sfLm.png)

**Comment by ArunBohra12** [comment]
@cjlovelace are you still working on this? Or can I take this one?

**Comment by cjlovelace** [comment]
Hi - happy to pass this off to you. This semester at college has gotten busy!

**Comment by ArunBohra12** [comment]
ok. But @aditya-singh9 do we need it or should we just drop it?

**Comment by aditya-singh9** [comment]
Um,there is a title thingy now so i guess we should drop this
