### ISSUE TITLE
Not obvious how to start using the app

### ISSUE THREAD

**Issue by mantevian** [aditya-singh9/notem#23]
When you first load Notem, there are only the 4 dots to change themes on the screen, and I genuinely had no idea how to create a note, because it's usually done with a button. I suggest adding a label that tells the user to click and drag to create a note, and the label would disappear after the first note was created. Also maybe a "select theme" label could be added to signify what the dots are for.
I could take on implementing this suggestion.

**Comment by aditya-singh9** [comment]
https://github.com/aditya-singh9/notem/issues/18

**Comment by mantevian** [comment]
oops, not sure how I missed that, sorry!
