### ISSUE TITLE
Font switcher

### ISSUE THREAD

**Issue by NalinPlad** [aditya-singh9/notem#25]
Add a font switch option, maybe to something more readable. I can work on this right after I finish up the peristaltic theme

**Comment by NalinPlad** [comment]
@aditya-singh9 do you have any font preferences for what to add, or should I just pick a few

**Comment by aditya-singh9** [comment]
Some of my favourite fonts are poppins, Montserrat and lexend exa.

Iguess i will go with lexend exa to be the default font of the notes.

1. [Lexend exa](https://fonts.google.com/specimen/Lexend%2BExa)
2. [Montserrat](https://fonts.google.com/specimen/Montserrat)
3. [Poppins](https://fonts.google.com/specimen/Poppins)
4. [Raleway](https://fonts.google.com/specimen/Raleway)
5. [Noto Sans](https://fonts.google.com/noto/specimen/Noto%2BSans%2BMono)
6. [PT sans](https://fonts.google.com/specimen/PT%2BSans)
7. [Roboto](https://fonts.google.com/specimen/Roboto)

You can suggest more fonts in thr comments, if you want.

**Comment by NalinPlad** [comment]
Almost done with it; will upload a prototype soon

**Comment by NalinPlad** [comment]
I left pixel as default font for now

**Comment by aditya-singh9** [comment]
Pixel seems unable to read
We can do lexend exa as default iguuess
What do you suggest?

**Comment by NalinPlad** [comment]
I agree pixel is hard to read. I can change the default to lexend exa.

**Comment by aditya-singh9** [comment]
can you pls look into https://github.com/aditya-singh9/notem/issues/38
