### ISSUE TITLE
Add a favicon to the website

### ISSUE THREAD

**Issue by Laxmankohar** [aditya-singh9/notem#41]
Since there is no favicon currently we can put one there.
This issue is opened under Hacktoberfest 2022.
I would like to work on this issue.

**Comment by aditya-singh9** [comment]
Actually, i would like to do that personally myself

It is not there for a reason.
I feel that adding just a favicon is not a good contribution to the repo.

But, if you have any suggestions about the favicon please add them in comments.


And if you want to make any significant changes to the webapp, you can open an issue and contribute.
Thanks
