### ISSUE TITLE
It doesn't remember the color of the note when refreshed

### ISSUE THREAD

**Issue by ArunBohra12** [aditya-singh9/notem#7]
Whenever we refresh the page. The notes are there but the background of those notes is still yellow. Instead it should be the color selected by the user?

**Comment by aditya-singh9** [comment]
Do you want to fix it?

**Comment by ArunBohra12** [comment]
Yes, I want to. Additionally can we set it up so that different notes can have different color?

**Comment by aditya-singh9** [comment]
yep, we can do that i have no problem with that

**Comment by yamitrvg12** [comment]
Hey [ArunBohra12](https://github.com/ArunBohra12), can you assign me this issue so that I can work on it?

**Comment by aditya-singh9** [comment]
He is already working on this issue.
Feel free to create an new issue about fixing or adding something else

**Comment by ArunBohra12** [comment]
Actually I haven't started yet so you can take it if you want.

**Comment by aditya-singh9** [comment]
@ArunBohra12 please confirm about assigning it to @yamitrvg12

**Comment by ArunBohra12** [comment]
Sure you can assign it to @yamitrvg12

**Comment by yamitrvg12** [comment]
working on it :)

**Comment by yamitrvg12** [comment]
Hey [aditya-singh9](https://github.com/aditya-singh9) I have completed this issue https://github.com/aditya-singh9/notem/pull/14. Could you please take a look it and if everything is OK could you please merge and add the "hacktoberfest-accepted" tag to it. Thank you!
