### ISSUE TITLE
Can we setup a proper dev server with npm using vite?

### ISSUE THREAD

**Issue by ArunBohra12** [aditya-singh9/notem#8]
Currently, in development, there is no proper env. If a dev doesn't have some sort of live server installed on their machine they would have to refresh the page again and again or even if they have all of them won't have one kind of server.

We can use vite which allows us to use HMR and is super easy to use.

**Comment by ArunBohra12** [comment]
Added the pull request for the same #11 

Might need to add the build command for the production

**Comment by aditya-singh9** [comment]
yep, i have merged it
